# Generated by Django 3.0 on 2024-02-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=500)),
                ('owner_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('mobile_number', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
