# Generated by Django 3.0 on 2024-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0005_auto_20240217_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
