# Generated by Django 3.0 on 2024-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0007_auto_20240225_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.CharField(default='0', max_length=20)),
                ('url', models.CharField(blank=True, default='N/A', max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scraperdetail',
            name='country_name',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scraperdetail',
            name='url',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdetail',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='scraperdetail',
            unique_together={('country_name', 'url')},
        ),
    ]
