# Generated by Django 3.0 on 2024-02-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0009_auto_20240228_1304'),
        ('knx', '0008_auto_20240228_1409'),
    ]

    operations = [
    ]
