# Generated by Django 3.0 on 2024-02-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0010_merge_20240228_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcount',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
