# Generated by Django 3.0 on 2024-02-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0011_auto_20240228_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlCount',
        ),
    ]
