# Generated by Django 3.0 on 2024-02-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0012_delete_urlcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('url', models.CharField(blank=True, default='N/A', max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
