# Generated by Django 3.0 on 2024-03-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0013_urlcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesData',
            fields=[
                ('uid', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salutation_id', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('stars_feedback', models.IntegerField()),
                ('stars_projects', models.IntegerField()),
                ('stars_engagement', models.IntegerField()),
                ('stars_tools', models.IntegerField()),
                ('stars_knowledge', models.IntegerField()),
                ('score_feedback', models.IntegerField()),
                ('score_projects', models.IntegerField()),
                ('score_engagement', models.IntegerField()),
                ('score_tools', models.IntegerField()),
                ('score_knowledge', models.IntegerField()),
                ('score', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('visible_list', models.BooleanField()),
                ('visible_map', models.BooleanField()),
                ('national_group_visible', models.BooleanField()),
                ('username', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('housenumber', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('country_id', models.IntegerField()),
                ('vat', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('language', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('communication_journal', models.TextField()),
                ('communication_journal_language_id', models.IntegerField()),
            ],
        ),
    ]
