# Generated by Django 3.0 on 2024-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0014_companiesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiesdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companiesdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
