# Generated by Django 3.0 on 2024-03-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0015_auto_20240309_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesdata',
            name='city',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='communication_journal',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='communication_journal_language_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='company',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='country_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='email',
            field=models.EmailField(default='NA', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='firstname',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='housenumber',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='language',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='lastname',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='mobile',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='national_group_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='phone',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='salutation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='score_engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='score_feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='score_knowledge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='score_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='score_tools',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='stars_engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='stars_feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='stars_knowledge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='stars_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='stars_tools',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='street',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='uid',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='username',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='vat',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='visible_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='visible_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='website',
            field=models.URLField(default='NA'),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='zipcode',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
