# Generated by Django 3.0 on 2024-03-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0016_auto_20240309_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesdata',
            name='city',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='communication_journal',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='company',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='email',
            field=models.EmailField(default='N/A', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='firstname',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='housenumber',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='language',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='lastname',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='mobile',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='street',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='uid',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='username',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='vat',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='website',
            field=models.URLField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='companiesdata',
            name='zipcode',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
