# Generated by Django 3.0 on 2024-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knx', '0017_auto_20240309_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiesdata',
            name='country_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
